/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Start a session with username and password
     * @description Returns the session cookie and the per-session CSRF token.
     */
    post: operations["post-auth-login"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * End the session
     * @description Deletes the server-side session row and expires the cookie; a bearer call has no session to delete and does not revoke the token. Cookie-authenticated calls must send X-DLTOOL-CSRF.
     */
    post: operations["post-auth-logout"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Read the caller's account and CSRF token
     * @description What the SPA calls on boot to choose between the setup wizard, the login screen and the app shell. With bearer authentication the csrf_token is empty.
     */
    get: operations["get-auth-me"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/setup": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create the operator account with the one-time setup token
     * @description Callable only while the operator account does not exist. Every other endpoint answers 401 /problems/setup-required until it succeeds.
     */
    post: operations["post-auth-setup"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/system/info": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read system information */
    get: operations["get-system-info"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/tasks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List, filter and sort tasks
     * @description Cursor-paginated task list. state accepts a canonical state or a sidebar filter; an empty category or tag selects the uncategorised and untagged tasks. A cursor is bound to the filter and sort that issued it.
     */
    get: operations["list-tasks"];
    put?: never;
    /**
     * Create tasks from submitted URIs
     * @description Creates one queued task per accepted URI and reports the refused ones in rejected[]. Partial success is normal. No engine is contacted: the admission pass owns Engine.Add.
     */
    post: operations["create-tasks"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/tasks/actions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Apply bulk lifecycle actions
     * @description Applies one of the nine actions to up to 500 tasks and reports a per-id outcome, so one bad id never fails the batch. The queue actions rewrite dl-tool's own queue and contact no engine. delete_data is accepted but currently a no-op: local data removal arrives with a later task.
     */
    post: operations["task-actions"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/tasks/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read one task */
    get: operations["get-task"];
    put?: never;
    post?: never;
    /**
     * Remove a task with or without its data
     * @description Marks the task removed and, with delete_data=true, unlinks exactly the files recorded in task_files after re-checking every resolved path against the data roots. delete_data=false keeps every byte. force_complete=true completes the task instead of removing it. The response reports what happened, so a client never has to guess.
     */
    delete: operations["delete-task"];
    options?: never;
    head?: never;
    /**
     * Update a task
     * @description Partial update of the display name, category, tags, per-task rate limits, share limits and the sequential flag. Omitted fields are untouched; a non-nil tags array replaces the whole set. The rate limits reach a running task without restarting it.
     */
    patch: operations["patch-task"];
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ActionResult: {
      /** @description Why the action did not apply */
      detail?: string;
      /** @description The task id this outcome reports */
      id: string;
      /** @description Whether the action applied */
      ok: boolean;
      /** @description A problem slug; set only when ok is false */
      type?: string;
    };
    ActionsInputBody: {
      /**
       * @description The action applied to every id
       * @enum {string}
       */
      action:
        | "pause"
        | "resume"
        | "remove"
        | "recheck"
        | "force_complete"
        | "queue_top"
        | "queue_up"
        | "queue_down"
        | "queue_bottom";
      /** @description Only meaningful with remove; the data unlink arrives with the delete endpoint's own task */
      delete_data?: boolean;
      /** @description Task ids; one outcome per entry, in request order */
      ids: string[] | null;
    };
    ActionsOutputBody: {
      /** @description One outcome per requested id, in request order */
      results: components["schemas"]["ActionResult"][] | null;
    };
    AuthEnvelope: {
      /** @description Per-session token; send as X-DLTOOL-CSRF on cookie-authenticated mutations */
      csrf_token: string;
      /** @description The operator account */
      user: components["schemas"]["UserBody"];
    };
    CreateTasksBody: {
      /** @description Category name; must already exist */
      category?: string;
      /** @description Place content in <destination>/<manifest name>/ (applied by the admission pass) */
      create_subfolder?: boolean;
      /** @description Must resolve inside a configured data root; defaults to the first root */
      destination?: string;
      /**
       * @description Overrides the routing table when that engine accepts the URI
       * @enum {string}
       */
      engine?: "aria2" | "qbittorrent" | "ytdlp";
      /** @description Stored for auto-extract; never returned */
      extract_password?: string;
      /** @description Used for this request's ftp, ftps and sftp URIs only; never returned */
      ftp_credentials?: components["schemas"]["FTPCredentials"];
      /** @description Create in paused instead of queued */
      paused?: boolean;
      sequential?: boolean;
      /** @description Tag names; created on demand */
      tags?: string[] | null;
      /** @description One entry per download; http(s), ftp(s), sftp, magnet, bare infohash and the obfuscated schemes */
      uris: string[] | null;
    };
    CreateTasksOutputBody: {
      /** @description The full Task objects of the created tasks */
      created: components["schemas"]["TaskDTO"][] | null;
      /** @description One entry per URI the submission refused; empty when everything was created */
      rejected: components["schemas"]["RejectedURI"][] | null;
    };
    DeleteTaskOutputBody: {
      /**
       * Format: int64
       * @description Recorded byte total of the unlinked files
       */
      bytes_unlinked: number;
      /** @description Whether the recorded files were unlinked */
      delete_data: boolean;
      /**
       * Format: int64
       * @description Files actually unlinked
       */
      files_unlinked: number;
      /**
       * Format: int64
       * @description Recorded files that were already gone
       */
      missing: number;
      /** @description Whether the task entered the removed state */
      removed: boolean;
    };
    ErrorDetail: {
      /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
      location?: string;
      /** @description Error message text */
      message?: string;
      /** @description The value at the given location */
      value?: unknown;
    };
    ErrorModel: {
      /**
       * @description A human-readable explanation specific to this occurrence of the problem.
       * @example Property foo is required but is missing.
       */
      detail?: string;
      /** @description Optional list of individual error details */
      errors?: components["schemas"]["ErrorDetail"][] | null;
      /**
       * Format: uri
       * @description A URI reference that identifies the specific occurrence of the problem.
       * @example https://example.com/error-log/abc123
       */
      instance?: string;
      /**
       * Format: int64
       * @description HTTP status code
       * @example 400
       */
      status?: number;
      /**
       * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
       * @example Bad Request
       */
      title?: string;
      /**
       * Format: uri
       * @description A URI reference to human-readable documentation for the error.
       * @default about:blank
       * @example https://example.com/errors/example
       */
      type: string;
    };
    FTPCredentials: {
      password: string;
      username: string;
    };
    ListTasksOutputBody: {
      /** @description Full Task objects, ordered by the requested sort */
      items: components["schemas"]["TaskDTO"][] | null;
      /** @description Token for the next page; null on the last page */
      next_cursor: string | null;
      /**
       * Format: int64
       * @description Rows matching the filter, ignoring the cursor
       */
      total: number;
    };
    LoginInputBody: {
      /** @description Account password */
      password: string;
      /** @description Account username */
      username: string;
    };
    PatchTaskBody: {
      /** @description Category name; must already exist */
      category?: string;
      /**
       * Format: int64
       * @description Bytes/second; 0 means unlimited; applied to a running task without restarting it
       */
      dl_limit?: number;
      /** @description Display name only; files on disk are not renamed */
      name?: string;
      /**
       * Format: double
       * @description Share ratio at which seeding stops
       */
      ratio_limit?: number;
      /**
       * Format: int64
       * @description Seconds of seeding after which seeding stops
       */
      seeding_time_limit?: number;
      /** @description Download the files of a multi-file task in order */
      sequential?: boolean;
      /** @description Replaces the whole tag set; an empty array clears it */
      tags?: string[] | null;
      /**
       * Format: int64
       * @description As dl_limit, for the upload direction
       */
      ul_limit?: number;
    };
    RejectedURI: {
      detail: string;
      type: string;
      uri: string;
    };
    SetupInputBody: {
      /**
       * @description Preferred UI locale
       * @default en
       */
      locale: string;
      /** @description Account password, at least 12 characters */
      password: string;
      /** @description The one-time token printed at first boot */
      setup_token: string;
      /** @description Operator username */
      username: string;
    };
    SystemInfoOutputBody: {
      /** @description Build version of the dl-tool process */
      version: string;
    };
    TaskDTO: {
      /** Format: date-time */
      added_at: string;
      category: string | null;
      /** Format: date-time */
      completed_at: string | null;
      /** Format: int64 */
      completed_bytes: number;
      /** Format: int64 */
      connected_leechers: number;
      /** Format: int64 */
      connected_seeders: number;
      content_path: string | null;
      destination: string;
      /** Format: int64 */
      dl_limit: number;
      /** Format: int64 */
      download_rate: number;
      engine: string;
      error_code: string | null;
      error_message: string | null;
      /** Format: int64 */
      eta_seconds: number | null;
      /** Format: int64 */
      file_count: number | null;
      id: string;
      infohash_v1: string | null;
      infohash_v2: string | null;
      name: string;
      /** Format: double */
      progress: number;
      /** Format: int64 */
      queue_position: number | null;
      /** Format: double */
      ratio: number;
      /** Format: double */
      ratio_limit: number | null;
      requested_destination: string | null;
      /** Format: int64 */
      seeding_time_limit: number | null;
      sequential: boolean;
      source_kind: string;
      source_uri: string | null;
      /** Format: date-time */
      started_at: string | null;
      state: string;
      tags: string[] | null;
      /** Format: int64 */
      total_bytes: number | null;
      /** Format: int64 */
      total_peers: number;
      /** Format: int64 */
      ul_limit: number;
      /** Format: int64 */
      unzip_progress: number | null;
      /** Format: date-time */
      updated_at: string;
      /** Format: int64 */
      upload_rate: number;
      /** Format: int64 */
      uploaded_bytes: number;
    };
    UserBody: {
      /**
       * Format: date-time
       * @description RFC 3339 timestamp of account creation
       */
      created_at: string;
      /** @description Whether the account may log in */
      enabled: boolean;
      /** @description User id */
      id: string;
      /**
       * Format: date-time
       * @description RFC 3339 timestamp of the last successful login
       */
      last_login_at: string | null;
      /** @description Preferred UI locale */
      locale: string;
      /** @description Account username */
      username: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  "post-auth-login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginInputBody"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          "Cache-Control"?: string;
          "Set-Cookie"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthEnvelope"];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  "post-auth-logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No Content */
      204: {
        headers: {
          "Set-Cookie"?: string;
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  "get-auth-me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          "Cache-Control"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthEnvelope"];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  "post-auth-setup": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SetupInputBody"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          "Cache-Control"?: string;
          "Set-Cookie"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthEnvelope"];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  "get-system-info": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SystemInfoOutputBody"];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  "list-tasks": {
    parameters: {
      query?: {
        /** @description A canonical state, or a sidebar filter: all, downloading, completed, active, inactive, stopped, error */
        state?:
          | "all"
          | "active"
          | "checking"
          | "completed"
          | "downloading"
          | "error"
          | "extracting"
          | "inactive"
          | "moving"
          | "paused"
          | "queued"
          | "removed"
          | "seeding"
          | "stopped";
        /** @description Category name; the empty value selects uncategorised tasks */
        category?: string;
        /** @description Tag name; the empty value selects untagged tasks */
        tag?: string;
        /** @description Case-insensitive substring of name */
        q?: string;
        /** @description Sort column with an optional leading - to reverse; default -added_at */
        sort?: string;
        /** @description Page size */
        limit?: number;
        /** @description Opaque page token from a previous response */
        cursor?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ListTasksOutputBody"];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  "create-tasks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateTasksBody"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CreateTasksOutputBody"];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  "task-actions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ActionsInputBody"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ActionsOutputBody"];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  "get-task": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The tsk_ id of the task */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TaskDTO"];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  "delete-task": {
    parameters: {
      query?: {
        /** @description Also unlink the downloaded data; the only irreversible operation in the product */
        delete_data?: boolean;
        /** @description Move the incomplete data to the destination and mark the task completed instead of removing it */
        force_complete?: boolean;
      };
      header?: never;
      path: {
        /** @description The tsk_ id of the task */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DeleteTaskOutputBody"];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  "patch-task": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The tsk_ id of the task */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PatchTaskBody"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TaskDTO"];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
}
