package ytdlp

// ResidualOverrides maps each extractor name in extractors_residual.txt to the
// host suffixes that route its URIs (hostnames, lowercase, no port). It is
// hand-maintained: the generator tells you which names need entries on each
// regen, and the coverage test fails if any residual name lacks one. Hostname
// granularity is deliberate — row 3 answers "should yt-dlp see this URL";
// yt-dlp picks its own extractor later.
var ResidualOverrides = map[string][]string{
	"Allstar":               {"allstar.gg"},
	"AltCensoredChannel":    {"altcensored.com"},
	"Audiomack":             {"audiomack.com"},
	"AudiomackAlbum":        {"audiomack.com"},
	"Audius":                {"audius.co"},
	"BBCCoUk":               {"bbc.co.uk"},
	"BYUtv":                 {"byutv.org"},
	"BandcampUser":          {"bandcamp.com"},
	"CBC":                   {"cbc.ca"},
	"CBCPlayerPlaylist":     {"cbc.ca"},
	"CBSSportsEmbed":        {"cbssports.com", "247sports.com"},
	"CNN":                   {"cnn.com"},
	"CTVNews":               {"ctvnews.ca"},
	"DLFCorpus":             {"deutschlandfunk.de"},
	"DLiveStream":           {"dlive.tv"},
	"Dailymotion":           {"dailymotion.com", "dai.ly", "lequipe.fr"},
	"DailymotionUser":       {"dailymotion.com", "dai.ly"},
	"DangalPlay":            {"dangalplay.com"},
	"DiscoveryPlus":         {"discoveryplus.com"},
	"EpiconSeries":          {"epicon.in"},
	"FoxNewsArticle":        {"foxnews.com"},
	"GetCourseRu":           {"getcourse.ru", "getcourse.io", "academymel.online", "mani-beauty.com", "psbook.ru"},
	"GloboArticle":          {"globo.com"},
	"GoodGame":              {"goodgame.ru"},
	"HotStar":               {"hotstar.com"},
	"HuyaLive":              {"huya.com"},
	"IPrima":                {"iprima.cz"},
	"IdagioPlaylist":        {"idagio.com"},
	"IdagioRecording":       {"idagio.com"},
	"ImdbList":              {"imdb.com"},
	"Imgur":                 {"imgur.com"},
	"Instagram":             {"instagram.com"},
	"IviCompilation":        {"ivi.ru"},
	"Kick":                  {"kick.com"},
	"KnownDRM":              knownDRMHosts,
	"LePlaylist":            {"le.com"},
	"Mediaite":              {"mediaite.com"},
	"MindsChannel":          {"minds.com"},
	"Mixcloud":              {"mixcloud.com"},
	"Mxplayer":              {"mxplayer.in"},
	"NBA":                   {"nba.com"},
	"NBAWatch":              {"nba.com"},
	"NBCSports":             {"nbcsports.com"},
	"NRKPlaylist":           {"nrk.no"},
	"NTVCoJpCU":             {"ntv.co.jp"},
	"NYTimesArticle":        {"nytimes.com"},
	"NebulaChannel":         {"watchnebula.com", "nebula.app", "nebula.tv"},
	"NebulaClass":           {"watchnebula.com", "nebula.app", "nebula.tv"},
	"NekoHacker":            {"nekohacker.com"},
	"Omnyfm":                {"omny.fm"},
	"OmnyfmPlaylist":        {"omny.fm"},
	"PartiLivestream":       {"parti.com"},
	"PatreonCampaign":       {"patreon.com"},
	"PornHubPagedVideoList": pornhubHosts,
	"PornHubUser":           pornhubHosts,
	"RCS":                   {"corriere.it", "gazzetta.it"},
	"RTVCPlay":              {"rtvcplay.co"},
	"RTVEALaCarta":          {"rtve.es"},
	"RaiCultura":            {"raicultura.it"},
	"RaiNews":               {"rainews.it"},
	"RedBull":               {"redbull.com"},
	"RokfinChannel":         {"rokfin.com"},
	"Rumble":                {"rumble.com"},
	"SharePoint":            {"sharepoint.com"},
	"SimplecastEpisode":     {"simplecast.com"},
	"SimplecastPodcast":     {"simplecast.com"},
	"Sohu":                  {"tv.sohu.com"},
	"Soundcloud":            {"soundcloud.com"},
	"SovietsClosetPlaylist": {"sovietscloset.com"},
	"TV2Article":            {"tv2.no"},
	"TV2Hu":                 {"tv2play.hu"},
	"TV8ItPlaylist":         {"tv8.it"},
	"TVCArticle":            {"tvc.ru"},
	"TVN24":                 {"tvn24.pl", "tvn24bis.pl"},
	"TVP":                   {"tvp.pl", "tvp.info", "tvpparlament.pl", "tvpparlament.info", "tvpworld.com", "swipeto.pl"},
	"TVPVODVideo":           {"tvp.pl"},
	"TarangPlusVideo":       {"tarangplus.in"},
	"ThisOldHouse":          {"thisoldhouse.com"},
	"ToypicsUser":           {"toypics.net"},
	// UnicodeBOM's pattern is a leading-\ufeff match from the commonmistakes
	// module — no hostname can carry it, so no host suffix can route it. The
	// entry exists because the coverage test requires one per residual name;
	// it can never match.
	"UnicodeBOM":        {"\ufeff"},
	"VKUserVideos":      {"vk.com", "vkvideo.ru"},
	"Vevo":              {"vevo.com"},
	"Vimeo":             {"vimeo.com"},
	"VimeoGroups":       {"vimeo.com"},
	"VimeoUser":         {"vimeo.com"},
	"WDR":               {"wdr.de"},
	"YouPornVideos":     {"youporn.com"},
	"Youtube":           youtubeHosts,
	"YoutubeTab":        youtubeHosts,
	"YoutubeWebArchive": {"web.archive.org"},
	"ZenYandexChannel":  {"zen.yandex.ru", "dzen.ru"},
}

// youtubeHosts are the first-party YouTube properties the residual Youtube
// patterns claim; the long tail of third-party mirrors in _VALID_URL (dead
// Invidious and Piped instances) is deliberately untracked.
var youtubeHosts = []string{
	"youtube.com",
	"youtu.be",
	"youtube-nocookie.com",
	"youtubekids.com",
	"youtube.googleapis.com",
}

// pornhubHosts is the PornHub alternation's TLD set, premium included.
var pornhubHosts = []string{
	"pornhub.com",
	"pornhub.net",
	"pornhub.org",
	"pornhubpremium.com",
	"pornhubpremium.net",
	"pornhubpremium.org",
}

// knownDRMHosts are the services the KnownDRM extractor claims so yt-dlp can
// answer with its DRM notice instead of aria2 downloading a portal page. The
// amazon entry covers the store TLDs whose /gp/video and music paths the
// pattern names.
var knownDRMHosts = []string{
	"hbomax.com",
	"channel4.com",
	"channel5.com",
	"peacocktv.com",
	"disneyplus.com",
	"spotify.com",
	"tvnz.co.nz",
	"oneplus.ch",
	"artstation.com",
	"philo.com",
	"mech-plus.com",
	"aha.video",
	"mubi.com",
	"vootkids.com",
	"nowtv.it",
	"tv.apple.com",
	"primevideo.com",
	"hulu.com",
	"inkryptvideos.com",
	"joyn.de",
	"amazon.com",
	"amazon.co.uk",
	"amazon.de",
	"amazon.fr",
	"amazon.it",
	"amazon.es",
	"amazon.ca",
	"amazon.co.jp",
	"amazon.com.au",
	"amazon.in",
	"njpwworld.com",
	"qub.ca",
	"crunchyroll.com",
	"viki.com",
	"deezer.com",
	"b-ch.com",
	"ctv.ca",
	"noovo.ca",
	"tsn.ca",
	"paramountplus.com",
	"crackle.com",
	"sonycrackle.com",
	"cwtv.com",
	"cwtvpr.com",
	"cwseed.com",
	"6play.fr",
	"rtlplay.be",
	"rtl.hr",
	"rtlmost.hu",
	"rtl.de",
	"mediasetinfinity.es",
	"tv5mondeplus.com",
	"rakuten.co.jp",
	"telusoriginals.com",
	"unext.jp",
	"web.nhk",
	"fujitv.co.jp",
	"zee5.com",
}
